// v1.0/demo/nextjs/src/modules/notes/notes.view.tsx
/**
 * @demo/notes — module-owned UI
 */

"use client";

import { useEffect, useRef, useState } from "react";

import { DEFAULT_CONFIG } from "../configuration/configuration.wmep";
import { createLogger } from "../../lib/host";

import { Notes, type Note } from "./notes.wmep";

import "./notes.scss";

export interface NotesViewProps {
  maxNotes?: number;
}

export function NotesView({
  maxNotes = DEFAULT_CONFIG.notes.maxNotes,
}: NotesViewProps): React.ReactElement {
  const [list, setList] = useState<Note[]>([]);
  const [draft, setDraft] = useState<string>("");
  const instanceRef = useRef<ReturnType<typeof Notes> | null>(null);

  useEffect(() => {
    const notes = Notes(
      { logger: createLogger("@demo/notes") },
      { maxNotes, seed: [] },
    );
    instanceRef.current = notes;

    const refresh = () => setList(notes.capabilities.getAll());

    const off = [
      notes.on("note:added", refresh),
      notes.on("note:edited", refresh),
      notes.on("note:removed", refresh),
      notes.on("notes:cleared", refresh),
      notes.on("wmep:mounted", refresh),
    ];

    return () => {
      off.forEach((fn) => fn());
      void notes.unmount("notes-view-unmount");
    };
  }, [maxNotes]);

  const submit = () => {
    const text = draft.trim();
    if (!text) return;
    instanceRef.current?.capabilities.add({ text });
    setDraft("");
  };

  return (
    <section className="module-panel notes-panel">
      <header className="module-panel-header">
        <span className="module-panel-title">Notes</span>
        <span className="module-panel-subtitle">
          @demo/notes &middot; {list.length} / {maxNotes}
        </span>
      </header>

      <div className="notes-composer">
        <input
          className="notes-input"
          value={draft}
          placeholder="Type a note and press Enter"
          onChange={(e) => setDraft(e.target.value)}
          onKeyDown={(e) => {
            if (e.key === "Enter") submit();
          }}
        />
        <button className="btn btn-green" onClick={submit}>
          Add
        </button>
        <button
          className="btn btn-ghost"
          onClick={() => instanceRef.current?.capabilities.clear()}
        >
          Clear
        </button>
      </div>

      <ul className="notes-list">
        {list.length === 0 ? (
          <li className="notes-empty">No notes yet.</li>
        ) : (
          list.map((n) => (
            <li key={n.id} className="notes-item">
              <span className="notes-item-text">{n.text}</span>
              <div className="notes-item-actions">
                <button
                  className="btn btn-ghost btn-xs"
                  onClick={() => {
                    const next = prompt("Edit note", n.text);
                    if (next != null && next.trim()) {
                      instanceRef.current?.capabilities.edit({
                        id: n.id,
                        text: next.trim(),
                      });
                    }
                  }}
                >
                  Edit
                </button>
                <button
                  className="btn btn-red btn-xs"
                  onClick={() =>
                    instanceRef.current?.capabilities.remove({ id: n.id })
                  }
                >
                  Delete
                </button>
              </div>
            </li>
          ))
        )}
      </ul>
    </section>
  );
}

// v1.0/demo/svelte/src/modules/notes/notes.view.svelte
<!--
  @demo/notes — module-owned UI (Svelte 5)
-->
<script lang="ts">
  import { onMount, onDestroy } from "svelte";

  import type { WmepInstance } from "@aurorah/wmep";

  import { DEFAULT_CONFIG } from "../configuration/configuration.wmep";
  import { createLogger } from "../../lib/host";

  import { Notes, type Note } from "./notes.wmep";

  import "./notes.scss";

  type Props = {
    maxNotes?: number;
  };

  let { maxNotes = DEFAULT_CONFIG.notes.maxNotes }: Props = $props();

  let list = $state<Note[]>([]);
  let draft = $state("");

  let instance: WmepInstance<Notes> | null = null;
  let unsubs: Array<() => void> = [];

  onMount(() => {
    const inst = Notes(
      { logger: createLogger("@demo/notes") },
      { maxNotes, seed: [] },
    );
    instance = inst;

    const refresh = () => {
      list = inst.capabilities.getAll();
    };

    unsubs.push(
      inst.on("note:added", refresh),
      inst.on("note:edited", refresh),
      inst.on("note:removed", refresh),
      inst.on("notes:cleared", refresh),
      inst.on("wmep:mounted", refresh),
    );
  });

  onDestroy(() => {
    unsubs.forEach((fn) => fn());
    unsubs = [];
    const inst = instance;
    instance = null;
    if (inst) void inst.unmount("notes-view-disconnect");
  });

  const submit = (): void => {
    const text = draft.trim();
    if (!text) return;
    try {
      instance?.capabilities.add({ text });
      draft = "";
    } catch (err) {
      console.warn(err);
    }
  };

  const editNote = (n: Note): void => {
    const next = prompt("Edit note", n.text);
    if (next != null && next.trim()) {
      instance?.capabilities.edit({ id: n.id, text: next.trim() });
    }
  };

  const removeNote = (id: string): void => {
    instance?.capabilities.remove({ id });
  };

  const clearAll = (): void => {
    instance?.capabilities.clear();
  };

  const onInputKeydown = (e: KeyboardEvent): void => {
    if (e.key === "Enter") submit();
  };
</script>

<section class="module-panel notes-panel">
  <header class="module-panel-header">
    <span class="module-panel-title">Notes</span>
    <span class="module-panel-subtitle">
      @demo/notes &middot; {list.length} / {maxNotes}
    </span>
  </header>

  <div class="notes-composer">
    <input
      class="notes-input"
      type="text"
      placeholder="Type a note and press Enter"
      bind:value={draft}
      onkeydown={onInputKeydown}
    />
    <button class="btn btn-green" onclick={submit}>Add</button>
    <button class="btn btn-ghost" onclick={clearAll}>Clear</button>
  </div>

  <ul class="notes-list">
    {#if list.length === 0}
      <li class="notes-empty">No notes yet.</li>
    {:else}
      {#each list as n (n.id)}
        <li class="notes-item">
          <span class="notes-item-text">{n.text}</span>
          <div class="notes-item-actions">
            <button class="btn btn-ghost btn-xs" onclick={() => editNote(n)}>
              Edit
            </button>
            <button class="btn btn-red btn-xs" onclick={() => removeNote(n.id)}>
              Delete
            </button>
          </div>
        </li>
      {/each}
    {/if}
  </ul>
</section>
